[build]
dockerfile = "Dockerfile"

[deploy]
startCommand = "/bin/sh -c \"sed -i 's/listen 80/listen ${PORT:-80}/g' /etc/nginx/sites-enabled/default && supervisord -c /etc/supervisor/conf.d/supervisord.conf\""
healthcheckPath = "/health"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
